package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Review;
import org.apache.ibatis.annotations.Param;

public interface ReviewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.REVIEW
     *
     * @mbg.generated Wed May 25 10:34:57 EEST 2022
     */
    int deleteByPrimaryKey(@Param("articleId") Integer articleId, @Param("userId") Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.REVIEW
     *
     * @mbg.generated Wed May 25 10:34:57 EEST 2022
     */
    int insert(Review record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.REVIEW
     *
     * @mbg.generated Wed May 25 10:34:57 EEST 2022
     */
    Review selectByPrimaryKey(@Param("articleId") Integer articleId, @Param("userId") Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.REVIEW
     *
     * @mbg.generated Wed May 25 10:34:57 EEST 2022
     */
    List<Review> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.REVIEW
     *
     * @mbg.generated Wed May 25 10:34:57 EEST 2022
     */
    int updateByPrimaryKey(Review record);
}