package lt.vu.mybatis.model;

public class Article {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ARTICLE.ID
     *
     * @mbg.generated Wed May 25 10:34:57 EEST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ARTICLE.CONTENT
     *
     * @mbg.generated Wed May 25 10:34:57 EEST 2022
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ARTICLE.TITLE
     *
     * @mbg.generated Wed May 25 10:34:57 EEST 2022
     */
    private String title;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ARTICLE.ID
     *
     * @return the value of PUBLIC.ARTICLE.ID
     *
     * @mbg.generated Wed May 25 10:34:57 EEST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ARTICLE.ID
     *
     * @param id the value for PUBLIC.ARTICLE.ID
     *
     * @mbg.generated Wed May 25 10:34:57 EEST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ARTICLE.CONTENT
     *
     * @return the value of PUBLIC.ARTICLE.CONTENT
     *
     * @mbg.generated Wed May 25 10:34:57 EEST 2022
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ARTICLE.CONTENT
     *
     * @param content the value for PUBLIC.ARTICLE.CONTENT
     *
     * @mbg.generated Wed May 25 10:34:57 EEST 2022
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ARTICLE.TITLE
     *
     * @return the value of PUBLIC.ARTICLE.TITLE
     *
     * @mbg.generated Wed May 25 10:34:57 EEST 2022
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ARTICLE.TITLE
     *
     * @param title the value for PUBLIC.ARTICLE.TITLE
     *
     * @mbg.generated Wed May 25 10:34:57 EEST 2022
     */
    public void setTitle(String title) {
        this.title = title;
    }
}