package lt.vu.mybatis.model;

public class Review {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.REVIEW.ARTICLE_ID
     *
     * @mbg.generated Wed May 25 10:34:57 EEST 2022
     */
    private Integer articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.REVIEW.USER_ID
     *
     * @mbg.generated Wed May 25 10:34:57 EEST 2022
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.REVIEW.CONTENT
     *
     * @mbg.generated Wed May 25 10:34:57 EEST 2022
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.REVIEW.RATING
     *
     * @mbg.generated Wed May 25 10:34:57 EEST 2022
     */
    private Integer rating;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.REVIEW.ARTICLE_ID
     *
     * @return the value of PUBLIC.REVIEW.ARTICLE_ID
     *
     * @mbg.generated Wed May 25 10:34:57 EEST 2022
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.REVIEW.ARTICLE_ID
     *
     * @param articleId the value for PUBLIC.REVIEW.ARTICLE_ID
     *
     * @mbg.generated Wed May 25 10:34:57 EEST 2022
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.REVIEW.USER_ID
     *
     * @return the value of PUBLIC.REVIEW.USER_ID
     *
     * @mbg.generated Wed May 25 10:34:57 EEST 2022
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.REVIEW.USER_ID
     *
     * @param userId the value for PUBLIC.REVIEW.USER_ID
     *
     * @mbg.generated Wed May 25 10:34:57 EEST 2022
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.REVIEW.CONTENT
     *
     * @return the value of PUBLIC.REVIEW.CONTENT
     *
     * @mbg.generated Wed May 25 10:34:57 EEST 2022
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.REVIEW.CONTENT
     *
     * @param content the value for PUBLIC.REVIEW.CONTENT
     *
     * @mbg.generated Wed May 25 10:34:57 EEST 2022
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.REVIEW.RATING
     *
     * @return the value of PUBLIC.REVIEW.RATING
     *
     * @mbg.generated Wed May 25 10:34:57 EEST 2022
     */
    public Integer getRating() {
        return rating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.REVIEW.RATING
     *
     * @param rating the value for PUBLIC.REVIEW.RATING
     *
     * @mbg.generated Wed May 25 10:34:57 EEST 2022
     */
    public void setRating(Integer rating) {
        this.rating = rating;
    }
}